//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace facebook
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="logins", Namespace="http://schemas.datacontract.org/2004/07/facebook.DataContracts")]
    public partial class logins : object
    {
        
        private string passwordField;
        
        private string useridField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userid
        {
            get
            {
                return this.useridField;
            }
            set
            {
                this.useridField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userdata", Namespace="http://schemas.datacontract.org/2004/07/facebook.DataContracts")]
    public partial class userdata : object
    {
        
        private string DegField;
        
        private string DeptField;
        
        private string IsVAliduserField;
        
        private string nameField;
        
        private string pwdchgstatusField;
        
        private string roleField;
        
        private string useridField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Deg
        {
            get
            {
                return this.DegField;
            }
            set
            {
                this.DegField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dept
        {
            get
            {
                return this.DeptField;
            }
            set
            {
                this.DeptField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsVAliduser
        {
            get
            {
                return this.IsVAliduserField;
            }
            set
            {
                this.IsVAliduserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pwdchgstatus
        {
            get
            {
                return this.pwdchgstatusField;
            }
            set
            {
                this.pwdchgstatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userid
        {
            get
            {
                return this.useridField;
            }
            set
            {
                this.useridField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="facebook.Ifacebookservices")]
    public interface Ifacebookservices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifacebookservices/getuserdetails", ReplyAction="http://tempuri.org/Ifacebookservices/getuserdetailsResponse")]
        System.Threading.Tasks.Task<facebook.userdata> getuserdetailsAsync(facebook.logins login);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IfacebookservicesChannel : facebook.Ifacebookservices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class IfacebookservicesClient : System.ServiceModel.ClientBase<facebook.Ifacebookservices>, facebook.Ifacebookservices
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IfacebookservicesClient() : 
                base(IfacebookservicesClient.GetDefaultBinding(), IfacebookservicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_Ifacebookservices.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IfacebookservicesClient(EndpointConfiguration endpointConfiguration) : 
                base(IfacebookservicesClient.GetBindingForEndpoint(endpointConfiguration), IfacebookservicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IfacebookservicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IfacebookservicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IfacebookservicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IfacebookservicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IfacebookservicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<facebook.userdata> getuserdetailsAsync(facebook.logins login)
        {
            return base.Channel.getuserdetailsAsync(login);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Ifacebookservices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Ifacebookservices))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:61124/facebookservices.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IfacebookservicesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_Ifacebookservices);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IfacebookservicesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_Ifacebookservices);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_Ifacebookservices,
        }
    }
}
